function openModal(title,eyebrow,html,onSave){ $('#modalTitle').textContent=title; $('#modalEyebrow').textContent=eyebrow; $('#modalBody').innerHTML=html; modalSaveHandler=onSave; $('#modal').showModal(); }
$('#modalForm').addEventListener('submit',e=>{ if(e.submitter?.value==='cancel'){modalSaveHandler=null;return;} e.preventDefault(); if(modalSaveHandler && modalSaveHandler()!==false){modalSaveHandler=null; $('#modal').close(); render();} });

$('#projectSelect').onchange=e=>{state.selectedProjectId=e.target.value; state.selectedTaskId=null; render();};
$('#newProjectBtn').onclick=()=>openModal('Tạo project','PROJECT','<input id="modalProjectName" placeholder="Tên project">',()=>{const n=$('#modalProjectName').value.trim(); if(!n)return false; const p={id:id(),name:n,createdAt:now()}; state.projects.push(p); state.selectedProjectId=p.id; return true;});
$('#newTaskFocusBtn').onclick=()=>$('#taskTitle').focus(); $('#taskSearch').oninput=renderTasks;
$('#startTaskBtn').onclick=()=>{const title=$('#taskTitle').value.trim(); const body=$('#taskBody').value.trim(); if(!body){toast('Nhập nội dung task trước');return;} const t={id:id(),projectId:state.selectedProjectId,title:title||body.slice(0,55),body,currentRole:'Developer',iteration:1,status:'In Progress',createdAt:now(),updatedAt:now(),results:[]}; state.tasks.unshift(t); state.selectedTaskId=t.id; log(t.id,'Developer','Task created','Developer activated'); scanIntegrations(body,t.id); $('#taskTitle').value=''; $('#taskBody').value=''; render();};
$('#editTaskBtn').onclick=()=>{const t=selectedTask(); if(!t)return; openModal('Sửa task','TASK',`<input id="modalTaskTitle" value="${escapeHtml(t.title)}"><textarea id="modalTaskBody" rows="9">${escapeHtml(t.body)}</textarea>`,()=>{const b=$('#modalTaskBody').value.trim(); if(!b)return false; t.title=$('#modalTaskTitle').value.trim()||b.slice(0,55);t.body=b;t.updatedAt=now();scanIntegrations(b,t.id);return true;});};
$('#deleteTaskBtn').onclick=()=>{const t=selectedTask(); if(!t)return; if(confirm(`Xóa task "${t.title}"?`)){state.tasks=state.tasks.filter(x=>x.id!==t.id);state.selectedTaskId=null;render();}};
$('#reopenTaskBtn').onclick=()=>{const t=selectedTask();if(!t||t.status!=='Done')return;t.status='In Progress';t.currentRole='Developer';t.iteration++;log(t.id,'Developer','Task reopened',`Iteration ${t.iteration}`);render();};
$('#copyPromptBtn').onclick=async()=>{const text=$('#promptOutput').value;if(!text)return;await navigator.clipboard.writeText(text);const t=selectedTask();if(t)log(t.id,t.currentRole,'Prompt copied','Clipboard');save();toast('Đã copy prompt');};
$('#openChatBtn').onclick=()=>{const t=selectedTask();if(!t)return;window.open(state.agents[t.currentRole]?.chatUrl||'https://chatgpt.com/','_blank','noopener');};
$('#resultInput').oninput=()=>{const t=selectedTask();const d=t?detectOutcome($('#resultInput').value,t.currentRole):null;$('#detectedOutcome').textContent=d?`Detected: ${d}`:'';if(d&&t?.currentRole!=='Developer')$('#outcomeSelect').value=d;scanIntegrations($('#resultInput').value,t?.id||null);save();renderPlugins();};
function record(send){const t=selectedTask();if(!t||t.status==='Done')return;const text=$('#resultInput').value.trim();if(!text){toast('Dán kết quả agent trước');return;}let outcome=$('#outcomeSelect').value;const detected=detectOutcome(text,t.currentRole);if(t.currentRole!=='Developer'&&detected)outcome=detected;const r={id:id(),role:t.currentRole,iteration:t.iteration,outcome,text,at:now()};t.results.push(r);log(t.id,t.currentRole,'Result recorded',outcome);scanIntegrations(text,t.id);if(send){const prev=t.currentRole;transition(t,outcome);log(t.id,t.currentRole,'Workflow transition',`${prev} ${outcome} → ${t.status==='Done'?'Done':t.currentRole}`);if(state.settings.autoOpenNext&&t.status!=='Done')window.open(state.agents[t.currentRole]?.chatUrl||'https://chatgpt.com/','_blank','noopener');}t.updatedAt=now();$('#resultInput').value='';$('#detectedOutcome').textContent='';render();}
$('#recordOnlyBtn').onclick=()=>record(false); $('#sendNextBtn').onclick=()=>record(true);

$$('.tab').forEach(btn=>btn.onclick=()=>{$$('.tab').forEach(x=>x.classList.remove('active'));$$('.tab-page').forEach(x=>x.classList.remove('active'));btn.classList.add('active');$(`#${btn.dataset.tab}Tab`).classList.add('active');});
$('#pluginSearch').oninput=renderPlugins; $('#pluginFilter').onchange=renderPlugins;
$('#addPluginBtn').onclick=()=>openModal('Add integration','PLUGIN',`<input id="pName" placeholder="Tên integration"><input id="pUrl" placeholder="Provider URL (optional)"><input id="pKeywords" placeholder="Keywords, cách nhau bằng dấu phẩy"><textarea id="pWhy" rows="3" placeholder="Vì sao cần integration này?"></textarea><textarea id="pPerms" rows="4" placeholder="Requested permissions, mỗi dòng một quyền"></textarea>`,()=>{const n=$('#pName').value.trim();if(!n)return false;state.integrations.push({id:`custom-${id()}`,name:n,url:$('#pUrl').value.trim(),keywords:$('#pKeywords').value.split(',').map(x=>x.trim()).filter(Boolean),why:$('#pWhy').value.trim()||'Custom integration',permissions:$('#pPerms').value.split('\n').map(x=>x.trim()).filter(Boolean),approval:'pending',requested:true,connection:'Not checked',custom:true});return true;});
$('#autoOpenNext').onchange=e=>{state.settings.autoOpenNext=e.target.checked;save();};
$('#exportBtn').onclick=()=>{const blob=new Blob([JSON.stringify(state,null,2)],{type:'application/json'});const a=document.createElement('a');a.href=URL.createObjectURL(blob);a.download=`ai-dev-team-${new Date().toISOString().slice(0,10)}.json`;a.click();URL.revokeObjectURL(a.href);};
$('#importInput').onchange=async e=>{const f=e.target.files?.[0];if(!f)return;try{const imported=JSON.parse(await f.text());if(!Array.isArray(imported.projects)||!Array.isArray(imported.tasks))throw new Error();state=imported;save();render();toast('Import thành công');}catch{alert('File JSON không hợp lệ.');}e.target.value='';};
$('#resetBtn').onclick=()=>{if(confirm('Reset toàn bộ dữ liệu AI Dev Team Web trên trình duyệt này?')){state=defaultState();state.selectedProjectId=state.projects[0].id;render();}};

render();
